name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22'

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Typecheck
        run: npm run typecheck

      - name: Knip
        run: npm run knip

      - name: Dependency cruiser
        run: npm run depcruise

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
