name: CI

on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - uses: jdx/mise-action@c37c93293d6b742fc901e1406b8f764f6fb19dac
        with:
          install: true

      - run: npm ci

      - name: Lint
        run: npm run lint

      - name: Format
        run: npm run format

      - name: Typecheck
        run: npm run typecheck

      - name: Knip
        run: npm run knip

      - name: Dependency cruiser
        run: npm run depcruise

      - name: Markdownlint
        run: npm run lint:md

      - name: Actionlint
        run: npm run lint:actions

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
